- name: install and run nginx
  hosts: web
  become: yes
  tasks: 
   - name: install nginx
    ansible.bultin.dnf:
      name: nginx
      state: latest
  - name: start nginx
    ansible.bultin.service:
      name: nginx
      state: started
      enabled: yes